#!/usr/bin/env python3
"""Build data/marketing_skill.xml from all skills/*/SKILL.md files."""

import os
import xml.sax.saxutils as saxutils

SKILLS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'skills')
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'marketing_core', 'data')
OUTPUT_FILE = os.path.join(OUTPUT_DIR, 'marketing_skill.xml')

CATEGORY_MAP = {
    'strategy': ['marketing-plan', 'marketing-ideas', 'marketing-loops',
                 'marketing-council', 'product-marketing', 'marketing-psychology',
                 'offers', 'pricing', 'launch'],
    'content': ['content-strategy', 'copywriting', 'copy-editing', 'social', 'video', 'image'],
    'acquisition': ['ads', 'ad-creative', 'cold-email', 'prospecting', 'lead-magnets', 'emails'],
    'seo': ['seo-audit', 'programmatic-seo', 'ai-seo', 'schema', 'site-architecture', 'aso',
            'directory-submissions'],
    'conversion': ['cro', 'ab-testing', 'signup', 'onboarding', 'popups', 'paywalls'],
    'retention': ['churn-prevention', 'sms'],
    'analytics': ['analytics', 'revops', 'competitors', 'competitor-profiling',
                  'customer-research'],
    'referral': ['referrals', 'co-marketing', 'community-marketing', 'free-tools',
                 'public-relations', 'sales-enablement'],
    'social': [],
}


def detect_category(name):
    for cat, names in CATEGORY_MAP.items():
        if name in names:
            return cat
    return 'strategy'


def parse_frontmatter(content):
    if not content.startswith('---'):
        return {}, content
    parts = content.split('---', 2)
    if len(parts) < 3:
        return {}, content
    fm = {}
    for line in parts[1].strip().split('\n'):
        line = line.strip()
        if ':' in line and not line.startswith('#'):
            key, val = line.split(':', 1)
            fm[key.strip()] = val.strip()
    return fm, parts[2].strip()


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    skills = []

    for skill_name in sorted(os.listdir(SKILLS_DIR)):
        skill_file = os.path.join(SKILLS_DIR, skill_name, 'SKILL.md')
        if not os.path.isfile(skill_file):
            continue
        with open(skill_file, 'r') as f:
            content = f.read()
        fm, body = parse_frontmatter(content)
        if not fm.get('name'):
            print(f"WARNING: {skill_file} has no name, skipping")
            continue
        skills.append({
            'name': fm['name'],
            'description': fm.get('description', ''),
            'category': detect_category(fm['name']),
            'version': '1.0.0',
            'body': body,
            'skill_path': f'skills/{skill_name}/SKILL.md',
        })

    xml = ['<?xml version="1.0" encoding="utf-8"?>', '<odoo>',
           '  <!-- Auto-generated by scripts/build_skill_xml.py -->', '']
    for s in skills:
        xml_id = f"marketing_skill_{s['name'].replace('-', '_')}"
        xml.append(f'  <record id="{xml_id}" model="marketing.skill">')
        xml.append(f'    <field name="name">{saxutils.escape(s["name"])}</field>')
        xml.append(f'    <field name="description">{saxutils.escape(s["description"])}</field>')
        xml.append(f'    <field name="category">{s["category"]}</field>')
        xml.append(f'    <field name="version">{s["version"]}</field>')
        xml.append(f'    <field name="skill_path">{saxutils.escape(s["skill_path"])}</field>')
        xml.append(f'    <field name="is_base" eval="True"/>')
        xml.append(f'    <field name="is_active" eval="True"/>')
        xml.append(f'    <field name="module_origin">marketing_core</field>')
        xml.append(f'    <field name="skill_content"><![CDATA[')
        xml.append(s['body'])
        xml.append(f']]></field>')
        xml.append(f'  </record>')
        xml.append('')
    xml.append('</odoo>')

    with open(OUTPUT_FILE, 'w') as f:
        f.write('\n'.join(xml))
    print(f"Generated {OUTPUT_FILE} with {len(skills)} skills")


if __name__ == '__main__':
    main()
