# Copyright (C) 2026 Vertel Sverige AB (<https://vertel.se>).
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import _, api, fields, models


class MarketingPlan(models.Model):
    """AARRR Marketing Plan — generated by Pi agents or created manually.
    Can reference a BMC from odoo-strategy for auto-population."""

    _name = 'marketing.plan'
    _description = 'Marketing Plan (AARRR)'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc, name'

    name = fields.Char('Plan Name', required=True)
    customer_id = fields.Many2one('res.partner', 'Customer',
        domain=[('customer_rank', '>', 0)], required=True)
    skill_id = fields.Many2one('marketing.skill', 'Generated By Skill')

    bmc_id = fields.Many2one('business.model.canvas', 'Business Model Canvas',
        help="Auto-populates plan sections from BMC")

    plan_markdown = fields.Text('Full Plan (Markdown)')

    executive_summary = fields.Html('Executive Summary')
    acquisition_strategy = fields.Html('Acquisition')
    activation_strategy = fields.Html('Activation')
    retention_strategy = fields.Html('Retention')
    referral_strategy = fields.Html('Referral')
    revenue_strategy = fields.Html('Revenue')

    start_date = fields.Date('Start Date')
    end_date = fields.Date('End Date')

    state = fields.Selection([
        ('draft', 'Draft'),
        ('active', 'Active'),
        ('completed', 'Completed'),
        ('archived', 'Archived'),
    ], string='Status', default='draft', required=True, tracking=True)

    generated_by = fields.Char('Generated By', default='pi-agent')
    skill_version = fields.Char('Skill Version')

    idea_ids = fields.Many2many('marketing.idea', string='Ideas Used')
    kpi_ids = fields.Many2many('marketing.kpi', string='KPIs')

    company_id = fields.Many2one('res.company', default=lambda self: self.env.company)
    user_id = fields.Many2one('res.users', 'Responsible',
        default=lambda self: self.env.user, tracking=True)

    @api.onchange('bmc_id')
    def _onchange_bmc(self):
        if self.bmc_id:
            bmc = self.bmc_id
            self.acquisition_strategy = bmc.customer_segments
            self.revenue_strategy = bmc.revenue_streams

    def action_activate(self):
        self.write({'state': 'active'})

    def action_complete(self):
        self.write({'state': 'completed'})

    def action_archive(self):
        self.write({'state': 'archived'})

    def action_draft(self):
        self.write({'state': 'draft'})
